INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.
; 30 pics per Sections
; trainers added after all pokemon sections

SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"

SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"

SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX
;15
RaltsFrontpic:              INCBIN "gfx/pokemon/ralts/front.animated.2bpp.lz"
RaltsBackpic:               INCBIN "gfx/pokemon/ralts/back.2bpp.lz"
KirliaFrontpic:             INCBIN "gfx/pokemon/kirlia/front.animated.2bpp.lz"
KirliaBackpic:              INCBIN "gfx/pokemon/kirlia/back.2bpp.lz"
GardevoirFrontpic:          INCBIN "gfx/pokemon/gardevoir/front.animated.2bpp.lz"
GardevoirBackpic:           INCBIN "gfx/pokemon/gardevoir/back.2bpp.lz"
GardevoirmFrontpic:         INCBIN "gfx/pokemon/gardevoirm/front.animated.2bpp.lz"
GardevoirmBackpic:          INCBIN "gfx/pokemon/gardevoirm/back.2bpp.lz"
ZigzagoonFrontpic:          INCBIN "gfx/pokemon/zigzagoon/front.animated.2bpp.lz"
ZigzagoonBackpic:           INCBIN "gfx/pokemon/zigzagoon/back.2bpp.lz"
LinooneFrontpic:            INCBIN "gfx/pokemon/linoone/front.animated.2bpp.lz"
LinooneBackpic:             INCBIN "gfx/pokemon/linoone/back.2bpp.lz"
WeedleFrontpic:             INCBIN "gfx/pokemon/weedle/front.animated.2bpp.lz"
WeedleBackpic:              INCBIN "gfx/pokemon/weedle/back.2bpp.lz"
KakunaFrontpic:             INCBIN "gfx/pokemon/kakuna/front.animated.2bpp.lz"
KakunaBackpic:              INCBIN "gfx/pokemon/kakuna/back.2bpp.lz"
BeedrillFrontpic:           INCBIN "gfx/pokemon/beedrill/front.animated.2bpp.lz"
BeedrillBackpic:            INCBIN "gfx/pokemon/beedrill/back.2bpp.lz"
StarlyFrontpic:             INCBIN "gfx/pokemon/starly/front.animated.2bpp.lz"
StarlyBackpic:              INCBIN "gfx/pokemon/starly/back.2bpp.lz"
StaraviaFrontpic:           INCBIN "gfx/pokemon/staravia/front.animated.2bpp.lz"
StaraviaBackpic:            INCBIN "gfx/pokemon/staravia/back.2bpp.lz"
StaraptorFrontpic:          INCBIN "gfx/pokemon/staraptor/front.animated.2bpp.lz"
StaraptorBackpic:           INCBIN "gfx/pokemon/staraptor/back.2bpp.lz"
ShinxFrontpic:              INCBIN "gfx/pokemon/shinx/front.animated.2bpp.lz"
ShinxBackpic:               INCBIN "gfx/pokemon/shinx/back.2bpp.lz"
LuxioFrontpic:              INCBIN "gfx/pokemon/luxio/front.animated.2bpp.lz"
LuxioBackpic:               INCBIN "gfx/pokemon/luxio/back.2bpp.lz"
LuxrayFrontpic:             INCBIN "gfx/pokemon/luxray/front.animated.2bpp.lz"
LuxrayBackpic:              INCBIN "gfx/pokemon/luxray/back.2bpp.lz"


SECTION "Pics 2", ROMX
;30
OddishFrontpic:             INCBIN "gfx/pokemon/oddish/front.animated.2bpp.lz"
OddishBackpic:              INCBIN "gfx/pokemon/oddish/back.2bpp.lz"
GloomFrontpic:              INCBIN "gfx/pokemon/gloom/front.animated.2bpp.lz"
GloomBackpic:               INCBIN "gfx/pokemon/gloom/back.2bpp.lz"
VileplumeFrontpic:          INCBIN "gfx/pokemon/vileplume/front.animated.2bpp.lz"
VileplumeBackpic:           INCBIN "gfx/pokemon/vileplume/back.2bpp.lz"
BellossomFrontpic:          INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
BellossomBackpic:           INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
PoliwagFrontpic:            INCBIN "gfx/pokemon/poliwag/front.animated.2bpp.lz"
PoliwagBackpic:             INCBIN "gfx/pokemon/poliwag/back.2bpp.lz"
PoliwhirlFrontpic:          INCBIN "gfx/pokemon/poliwhirl/front.animated.2bpp.lz"
PoliwhirlBackpic:           INCBIN "gfx/pokemon/poliwhirl/back.2bpp.lz"
PoliwrathFrontpic:          INCBIN "gfx/pokemon/poliwrath/front.animated.2bpp.lz"
PoliwrathBackpic:           INCBIN "gfx/pokemon/poliwrath/back.2bpp.lz"
PolitoedFrontpic:           INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
PolitoedBackpic:            INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
NidoranMFrontpic:           INCBIN "gfx/pokemon/nidoran_m/front.animated.2bpp.lz"
NidoranMBackpic:            INCBIN "gfx/pokemon/nidoran_m/back.2bpp.lz"
NidorinoFrontpic:           INCBIN "gfx/pokemon/nidorino/front.animated.2bpp.lz"
NidorinoBackpic:            INCBIN "gfx/pokemon/nidorino/back.2bpp.lz"
NidokingFrontpic:           INCBIN "gfx/pokemon/nidoking/front.animated.2bpp.lz"
NidokingBackpic:            INCBIN "gfx/pokemon/nidoking/back.2bpp.lz"
NidoranFFrontpic:           INCBIN "gfx/pokemon/nidoran_f/front.animated.2bpp.lz"
NidoranFBackpic:            INCBIN "gfx/pokemon/nidoran_f/back.2bpp.lz"
NidorinaFrontpic:           INCBIN "gfx/pokemon/nidorina/front.animated.2bpp.lz"
NidorinaBackpic:            INCBIN "gfx/pokemon/nidorina/back.2bpp.lz"
NidoqueenFrontpic:          INCBIN "gfx/pokemon/nidoqueen/front.animated.2bpp.lz"
NidoqueenBackpic:           INCBIN "gfx/pokemon/nidoqueen/back.2bpp.lz"
PikachuFrontpic:            INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
PikachuBackpic:             INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"


SECTION "Pics 3", ROMX
;45
RaichuFrontpic:             INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
RaichuBackpic:              INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
SandshrewFrontpic:          INCBIN "gfx/pokemon/sandshrew/front.animated.2bpp.lz"
SandshrewBackpic:           INCBIN "gfx/pokemon/sandshrew/back.2bpp.lz"
SandslashFrontpic:          INCBIN "gfx/pokemon/sandslash/front.animated.2bpp.lz"
SandslashBackpic:           INCBIN "gfx/pokemon/sandslash/back.2bpp.lz"
BulbasaurFrontpic:          INCBIN "gfx/pokemon/bulbasaur/front.animated.2bpp.lz"
BulbasaurBackpic:           INCBIN "gfx/pokemon/bulbasaur/back.2bpp.lz"
IvysaurFrontpic:            INCBIN "gfx/pokemon/ivysaur/front.animated.2bpp.lz"
IvysaurBackpic:             INCBIN "gfx/pokemon/ivysaur/back.2bpp.lz"
VenusaurFrontpic:           INCBIN "gfx/pokemon/venusaur/front.animated.2bpp.lz"
VenusaurBackpic:            INCBIN "gfx/pokemon/venusaur/back.2bpp.lz"
CharmanderFrontpic:         INCBIN "gfx/pokemon/charmander/front.animated.2bpp.lz"
CharmanderBackpic:          INCBIN "gfx/pokemon/charmander/back.2bpp.lz"
CharmeleonFrontpic:         INCBIN "gfx/pokemon/charmeleon/front.animated.2bpp.lz"
CharmeleonBackpic:          INCBIN "gfx/pokemon/charmeleon/back.2bpp.lz"
CharizardFrontpic:          INCBIN "gfx/pokemon/charizard/front.animated.2bpp.lz"
CharizardBackpic:           INCBIN "gfx/pokemon/charizard/back.2bpp.lz"
SquirtleFrontpic:           INCBIN "gfx/pokemon/squirtle/front.animated.2bpp.lz"
SquirtleBackpic:            INCBIN "gfx/pokemon/squirtle/back.2bpp.lz"
WartortleFrontpic:          INCBIN "gfx/pokemon/wartortle/front.animated.2bpp.lz"
WartortleBackpic:           INCBIN "gfx/pokemon/wartortle/back.2bpp.lz"
BlastoiseFrontpic:          INCBIN "gfx/pokemon/blastoise/front.animated.2bpp.lz"
BlastoiseBackpic:           INCBIN "gfx/pokemon/blastoise/back.2bpp.lz"
ZubatFrontpic:              INCBIN "gfx/pokemon/zubat/front.animated.2bpp.lz"
ZubatBackpic:               INCBIN "gfx/pokemon/zubat/back.2bpp.lz"
GolbatFrontpic:             INCBIN "gfx/pokemon/golbat/front.animated.2bpp.lz"
GolbatBackpic:              INCBIN "gfx/pokemon/golbat/back.2bpp.lz"
CrobatFrontpic:             INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
CrobatBackpic:              INCBIN "gfx/pokemon/crobat/back.2bpp.lz"

SECTION "Pics 4", ROMX
;60
KoffingFrontpic:            INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
KoffingBackpic:             INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
WeezingFrontpic:            INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
WeezingBackpic:             INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
EkansFrontpic:              INCBIN "gfx/pokemon/ekans/front.animated.2bpp.lz"
EkansBackpic:               INCBIN "gfx/pokemon/ekans/back.2bpp.lz"
ArbokFrontpic:              INCBIN "gfx/pokemon/arbok/front.animated.2bpp.lz"
ArbokBackpic:               INCBIN "gfx/pokemon/arbok/back.2bpp.lz"
MeowthFrontpic:             INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
MeowthBackpic:              INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
PersianFrontpic:            INCBIN "gfx/pokemon/persian/front.animated.2bpp.lz"
PersianBackpic:             INCBIN "gfx/pokemon/persian/back.2bpp.lz"
CacneaFrontpic:             INCBIN "gfx/pokemon/cacnea/front.animated.2bpp.lz"
CacneaBackpic:              INCBIN "gfx/pokemon/cacnea/back.2bpp.lz"
CacturneFrontpic:           INCBIN "gfx/pokemon/cacturne/front.animated.2bpp.lz"
CacturneBackpic:            INCBIN "gfx/pokemon/cacturne/back.2bpp.lz"
WobbuffetFrontpic:          INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
WobbuffetBackpic:           INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
MawileFrontpic:             INCBIN "gfx/pokemon/mawile/front.animated.2bpp.lz"
MawileBackpic:              INCBIN "gfx/pokemon/mawile/back.2bpp.lz"
GeodudeFrontpic:            INCBIN "gfx/pokemon/geodude/front.animated.2bpp.lz"
GeodudeBackpic:             INCBIN "gfx/pokemon/geodude/back.2bpp.lz"
GravelerFrontpic:           INCBIN "gfx/pokemon/graveler/front.animated.2bpp.lz"
GravelerBackpic:            INCBIN "gfx/pokemon/graveler/back.2bpp.lz"
GolemFrontpic:              INCBIN "gfx/pokemon/golem/front.animated.2bpp.lz"
GolemBackpic:               INCBIN "gfx/pokemon/golem/back.2bpp.lz"
MachopFrontpic:             INCBIN "gfx/pokemon/machop/front.animated.2bpp.lz"
MachopBackpic:              INCBIN "gfx/pokemon/machop/back.2bpp.lz"
MachokeFrontpic:            INCBIN "gfx/pokemon/machoke/front.animated.2bpp.lz"
MachokeBackpic:             INCBIN "gfx/pokemon/machoke/back.2bpp.lz"


SECTION "Pics 5", ROMX
;75
MachampFrontpic:            INCBIN "gfx/pokemon/machamp/front.animated.2bpp.lz"
MachampBackpic:             INCBIN "gfx/pokemon/machamp/back.2bpp.lz"
AbraFrontpic:               INCBIN "gfx/pokemon/abra/front.animated.2bpp.lz"
AbraBackpic:                INCBIN "gfx/pokemon/abra/back.2bpp.lz"
KadabraFrontpic:            INCBIN "gfx/pokemon/kadabra/front.animated.2bpp.lz"
KadabraBackpic:             INCBIN "gfx/pokemon/kadabra/back.2bpp.lz"
AlakazamFrontpic:           INCBIN "gfx/pokemon/alakazam/front.animated.2bpp.lz"
AlakazamBackpic:            INCBIN "gfx/pokemon/alakazam/back.2bpp.lz"
GastlyFrontpic:             INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
GastlyBackpic:              INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
HaunterFrontpic:            INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
HaunterBackpic:             INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
GengarFrontpic:             INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
GengarBackpic:              INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
GrowlitheFrontpic:          INCBIN "gfx/pokemon/growlithe/front.animated.2bpp.lz"
GrowlitheBackpic:           INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
ArcanineFrontpic:           INCBIN "gfx/pokemon/arcanine/front.animated.2bpp.lz"
ArcanineBackpic:            INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
VulpixFrontpic:             INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
VulpixBackpic:              INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
NinetalesFrontpic:          INCBIN "gfx/pokemon/ninetales/front.animated.2bpp.lz"
NinetalesBackpic:           INCBIN "gfx/pokemon/ninetales/back.2bpp.lz"
PsyduckFrontpic:            INCBIN "gfx/pokemon/psyduck/front.animated.2bpp.lz"
PsyduckBackpic:             INCBIN "gfx/pokemon/psyduck/back.2bpp.lz"
GolduckFrontpic:            INCBIN "gfx/pokemon/golduck/front.animated.2bpp.lz"
GolduckBackpic:             INCBIN "gfx/pokemon/golduck/back.2bpp.lz"
TeddiursaFrontpic:          INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
TeddiursaBackpic:           INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
UrsaringFrontpic:           INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
UrsaringBackpic:            INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"


SECTION "Pics 6", ROMX
;90

MakuhitaFrontpic:           INCBIN "gfx/pokemon/makuhita/front.animated.2bpp.lz"
MakuhitaBackpic:            INCBIN "gfx/pokemon/makuhita/back.2bpp.lz"
HariyamaFrontpic:           INCBIN "gfx/pokemon/hariyama/front.animated.2bpp.lz"
HariyamaBackpic:            INCBIN "gfx/pokemon/hariyama/back.2bpp.lz"
MedititeFrontpic:           INCBIN "gfx/pokemon/meditite/front.animated.2bpp.lz"
MedititeBackpic:            INCBIN "gfx/pokemon/meditite/back.2bpp.lz"
MedichamFrontpic:           INCBIN "gfx/pokemon/medicham/front.animated.2bpp.lz"
MedichamBackpic:            INCBIN "gfx/pokemon/medicham/back.2bpp.lz"
ClefairyFrontpic:           INCBIN "gfx/pokemon/clefairy/front.animated.2bpp.lz"
ClefairyBackpic:            INCBIN "gfx/pokemon/clefairy/back.2bpp.lz"
ClefableFrontpic:           INCBIN "gfx/pokemon/clefable/front.animated.2bpp.lz"
ClefableBackpic:            INCBIN "gfx/pokemon/clefable/back.2bpp.lz"
OnixFrontpic:               INCBIN "gfx/pokemon/onix/front.animated.2bpp.lz"
OnixBackpic:                INCBIN "gfx/pokemon/onix/back.2bpp.lz"
SteelixFrontpic:            INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
SteelixBackpic:             INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
VenonatFrontpic:            INCBIN "gfx/pokemon/venonat/front.animated.2bpp.lz"
VenonatBackpic:             INCBIN "gfx/pokemon/venonat/back.2bpp.lz"
VenomothFrontpic:           INCBIN "gfx/pokemon/venomoth/front.animated.2bpp.lz"
VenomothBackpic:            INCBIN "gfx/pokemon/venomoth/back.2bpp.lz"
PinecoFrontpic:             INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
PinecoBackpic:              INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
ForretressFrontpic:         INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
ForretressBackpic:          INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
LotadFrontpic:              INCBIN "gfx/pokemon/lotad/front.animated.2bpp.lz"
LotadBackpic:               INCBIN "gfx/pokemon/lotad/back.2bpp.lz"
LombreFrontpic:             INCBIN "gfx/pokemon/lombre/front.animated.2bpp.lz"
LombreBackpic:              INCBIN "gfx/pokemon/lombre/back.2bpp.lz"
LudicoloFrontpic:           INCBIN "gfx/pokemon/ludicolo/front.animated.2bpp.lz"
LudicoloBackpic:            INCBIN "gfx/pokemon/ludicolo/back.2bpp.lz"

SECTION "Pics 7", ROMX
;105
GrimerFrontpic:             INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
GrimerBackpic:              INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
MukFrontpic:                INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
MukBackpic:                 INCBIN "gfx/pokemon/muk/back.2bpp.lz"
MagnemiteFrontpic:          INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
MagnemiteBackpic:           INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"
MagnetonFrontpic:           INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
MagnetonBackpic:            INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
MagnezoneFrontpic:          INCBIN "gfx/pokemon/magnezone/front.animated.2bpp.lz"
MagnezoneBackpic:           INCBIN "gfx/pokemon/magnezone/back.2bpp.lz"
CroagunkFrontpic:           INCBIN "gfx/pokemon/croagunk/front.animated.2bpp.lz"
CroagunkBackpic:            INCBIN "gfx/pokemon/croagunk/back.2bpp.lz"
ToxicroakFrontpic:          INCBIN "gfx/pokemon/toxicroak/front.animated.2bpp.lz"
ToxicroakBackpic:           INCBIN "gfx/pokemon/toxicroak/back.2bpp.lz"
PhanpyFrontpic:             INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
PhanpyBackpic:              INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
DonphanFrontpic:            INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
DonphanBackpic:             INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
MrMimeFrontpic:             INCBIN "gfx/pokemon/mrmime/front.animated.2bpp.lz"
MrMimeBackpic:              INCBIN "gfx/pokemon/mrmime/back.2bpp.lz"
BunearyFrontpic:            INCBIN "gfx/pokemon/buneary/front.animated.2bpp.lz"
BunearyBackpic:             INCBIN "gfx/pokemon/buneary/back.2bpp.lz"
LopunnyFrontpic:            INCBIN "gfx/pokemon/lopunny/front.animated.2bpp.lz"
LopunnyBackpic:             INCBIN "gfx/pokemon/lopunny/back.2bpp.lz"
ChikoritaFrontpic:          INCBIN "gfx/pokemon/chikorita/front.animated.2bpp.lz"
ChikoritaBackpic:           INCBIN "gfx/pokemon/chikorita/back.2bpp.lz"
BayleefFrontpic:            INCBIN "gfx/pokemon/bayleef/front.animated.2bpp.lz"
BayleefBackpic:             INCBIN "gfx/pokemon/bayleef/back.2bpp.lz"
MeganiumFrontpic:           INCBIN "gfx/pokemon/meganium/front.animated.2bpp.lz"
MeganiumBackpic:            INCBIN "gfx/pokemon/meganium/back.2bpp.lz"

SECTION "Pics 8", ROMX
;120
CyndaquilFrontpic:          INCBIN "gfx/pokemon/cyndaquil/front.animated.2bpp.lz"
CyndaquilBackpic:           INCBIN "gfx/pokemon/cyndaquil/back.2bpp.lz"
QuilavaFrontpic:            INCBIN "gfx/pokemon/quilava/front.animated.2bpp.lz"
QuilavaBackpic:             INCBIN "gfx/pokemon/quilava/back.2bpp.lz"
TyphlosionFrontpic:         INCBIN "gfx/pokemon/typhlosion/front.animated.2bpp.lz"
TyphlosionBackpic:          INCBIN "gfx/pokemon/typhlosion/back.2bpp.lz"
TotodileFrontpic:           INCBIN "gfx/pokemon/totodile/front.animated.2bpp.lz"
TotodileBackpic:            INCBIN "gfx/pokemon/totodile/back.2bpp.lz"
CroconawFrontpic:           INCBIN "gfx/pokemon/croconaw/front.animated.2bpp.lz"
CroconawBackpic:            INCBIN "gfx/pokemon/croconaw/back.2bpp.lz"
FeraligatrFrontpic:         INCBIN "gfx/pokemon/feraligatr/front.animated.2bpp.lz"
FeraligatrBackpic:          INCBIN "gfx/pokemon/feraligatr/back.2bpp.lz"
TaillowFrontpic:            INCBIN "gfx/pokemon/taillow/front.animated.2bpp.lz"
TaillowBackpic:             INCBIN "gfx/pokemon/taillow/back.2bpp.lz"
SwellowFrontpic:            INCBIN "gfx/pokemon/swellow/front.animated.2bpp.lz"
SwellowBackpic:             INCBIN "gfx/pokemon/swellow/back.2bpp.lz"
MareepFrontpic:             INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
MareepBackpic:              INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
FlaaffyFrontpic:            INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
FlaaffyBackpic:             INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
AmpharosFrontpic:           INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
AmpharosBackpic:            INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
FeebasFrontpic:             INCBIN "gfx/pokemon/feebas/front.animated.2bpp.lz"
FeebasBackpic:              INCBIN "gfx/pokemon/feebas/back.2bpp.lz"
MiloticFrontpic:            INCBIN "gfx/pokemon/milotic/front.animated.2bpp.lz"
MiloticBackpic:             INCBIN "gfx/pokemon/milotic/back.2bpp.lz"
MagikarpFrontpic:           INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
MagikarpBackpic:            INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
GyaradosFrontpic:           INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
GyaradosBackpic:            INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"


SECTION "Pics 9", ROMX
;135
SneaselFrontpic:            INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
SneaselBackpic:             INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
WeavileFrontpic:            INCBIN "gfx/pokemon/weavile/front.animated.2bpp.lz"
WeavileBackpic:             INCBIN "gfx/pokemon/weavile/back.2bpp.lz"
MurkrowFrontpic:            INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
MurkrowBackpic:             INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
HonchkrowFrontpic:          INCBIN "gfx/pokemon/honchkrow/front.animated.2bpp.lz"
HonchkrowBackpic:           INCBIN "gfx/pokemon/honchkrow/back.2bpp.lz"
MisdreavusFrontpic:         INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
MisdreavusBackpic:          INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
MismagiusFrontpic:          INCBIN "gfx/pokemon/mismagius/front.animated.2bpp.lz"
MismagiusBackpic:           INCBIN "gfx/pokemon/mismagius/back.2bpp.lz"
GligarFrontpic:             INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
GligarBackpic:              INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
GliscorFrontpic:            INCBIN "gfx/pokemon/gliscor/front.animated.2bpp.lz"
GliscorBackpic:             INCBIN "gfx/pokemon/gliscor/back.2bpp.lz"
HorseaFrontpic:             INCBIN "gfx/pokemon/horsea/front.animated.2bpp.lz"
HorseaBackpic:              INCBIN "gfx/pokemon/horsea/back.2bpp.lz"
SeadraFrontpic:             INCBIN "gfx/pokemon/seadra/front.animated.2bpp.lz"
SeadraBackpic:              INCBIN "gfx/pokemon/seadra/back.2bpp.lz"
KingdraFrontpic:            INCBIN "gfx/pokemon/kingdra/front.animated.2bpp.lz"
KingdraBackpic:             INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
SwinubFrontpic:             INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
SwinubBackpic:              INCBIN "gfx/pokemon/swinub/back.2bpp.lz"
PiloswineFrontpic:          INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
PiloswineBackpic:           INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
MamoswineFrontpic:          INCBIN "gfx/pokemon/mamoswine/front.animated.2bpp.lz"
MamoswineBackpic:           INCBIN "gfx/pokemon/mamoswine/back.2bpp.lz"
YanmaFrontpic:              INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
YanmaBackpic:               INCBIN "gfx/pokemon/yanma/back.2bpp.lz"


SECTION "Pics 10", ROMX
;150
YanmegaFrontpic:            INCBIN "gfx/pokemon/yanmega/front.animated.2bpp.lz"
YanmegaBackpic:             INCBIN "gfx/pokemon/yanmega/back.2bpp.lz"
MagmarFrontpic:             INCBIN "gfx/pokemon/magmar/front.animated.2bpp.lz"
MagmarBackpic:              INCBIN "gfx/pokemon/magmar/back.2bpp.lz"
MagmortarFrontpic:          INCBIN "gfx/pokemon/magmortar/front.animated.2bpp.lz"
MagmortarBackpic:           INCBIN "gfx/pokemon/magmortar/back.2bpp.lz"
ElectabuzzFrontpic:         INCBIN "gfx/pokemon/electabuzz/front.animated.2bpp.lz"
ElectabuzzBackpic:          INCBIN "gfx/pokemon/electabuzz/back.2bpp.lz"
ElectivireFrontpic:         INCBIN "gfx/pokemon/electivire/front.animated.2bpp.lz"
ElectivireBackpic:          INCBIN "gfx/pokemon/electivire/back.2bpp.lz"
HoundourFrontpic:           INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
HoundourBackpic:            INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
HoundoomFrontpic:           INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
HoundoomBackpic:            INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
StaryuFrontpic:             INCBIN "gfx/pokemon/staryu/front.animated.2bpp.lz"
StaryuBackpic:              INCBIN "gfx/pokemon/staryu/back.2bpp.lz"
StarmieFrontpic:            INCBIN "gfx/pokemon/starmie/front.animated.2bpp.lz"
StarmieBackpic:             INCBIN "gfx/pokemon/starmie/back.2bpp.lz"
ExeggcuteFrontpic:          INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
ExeggcuteBackpic:           INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"
ExeggutorFrontpic:          INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
ExeggutorBackpic:           INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
HeracrossFrontpic:          INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"
HeracrossBackpic:           INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
SkarmoryFrontpic:           INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
SkarmoryBackpic:            INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
TyrogueFrontpic:            INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
TyrogueBackpic:             INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
HitmonchanFrontpic:         INCBIN "gfx/pokemon/hitmonchan/front.animated.2bpp.lz"
HitmonchanBackpic:          INCBIN "gfx/pokemon/hitmonchan/back.2bpp.lz"





SECTION "Pics 11", ROMX
;165

HitmonleeFrontpic:          INCBIN "gfx/pokemon/hitmonlee/front.animated.2bpp.lz"
HitmonleeBackpic:           INCBIN "gfx/pokemon/hitmonlee/back.2bpp.lz"
NeroPic:                    INCBIN "gfx/trainers/nero.2bpp.lz"
Loreleil1Pic:               INCBIN "gfx/trainers/lorelei.2bpp.lz"
TreeckoFrontpic:             INCBIN "gfx/pokemon/treecko/front.animated.2bpp.lz"
TreeckoBackpic:              INCBIN "gfx/pokemon/treecko/back.2bpp.lz"
GrovyleFrontpic:            INCBIN "gfx/pokemon/grovyle/front.animated.2bpp.lz"
GrovyleBackpic:             INCBIN "gfx/pokemon/grovyle/back.2bpp.lz"
SceptileFrontpic:           INCBIN "gfx/pokemon/sceptile/front.animated.2bpp.lz"
SceptileBackpic:            INCBIN "gfx/pokemon/sceptile/back.2bpp.lz"
TorchicFrontpic:            INCBIN "gfx/pokemon/torchic/front.animated.2bpp.lz"
TorchicBackpic:             INCBIN "gfx/pokemon/torchic/back.2bpp.lz"
CombuskenFrontpic:          INCBIN "gfx/pokemon/combusken/front.animated.2bpp.lz"
CombuskenBackpic:           INCBIN "gfx/pokemon/combusken/back.2bpp.lz"
BlazikenFrontpic:           INCBIN "gfx/pokemon/blaziken/front.animated.2bpp.lz"
BlazikenBackpic:            INCBIN "gfx/pokemon/blaziken/back.2bpp.lz"
MudkipFrontpic:             INCBIN "gfx/pokemon/mudkip/front.animated.2bpp.lz"
MudkipBackpic:              INCBIN "gfx/pokemon/mudkip/back.2bpp.lz"
MarshtompFrontpic:          INCBIN "gfx/pokemon/marshtomp/front.animated.2bpp.lz"
MarshtompBackpic:           INCBIN "gfx/pokemon/marshtomp/back.2bpp.lz"
SwampertFrontpic:           INCBIN "gfx/pokemon/swampert/front.animated.2bpp.lz"
SwampertBackpic:            INCBIN "gfx/pokemon/swampert/back.2bpp.lz"
AronFrontpic:               INCBIN "gfx/pokemon/aron/front.animated.2bpp.lz"
AronBackpic:                INCBIN "gfx/pokemon/aron/back.2bpp.lz"
LaironFrontpic:             INCBIN "gfx/pokemon/lairon/front.animated.2bpp.lz"
LaironBackpic:              INCBIN "gfx/pokemon/lairon/back.2bpp.lz"
AggronFrontpic:             INCBIN "gfx/pokemon/aggron/front.animated.2bpp.lz"
AggronBackpic:              INCBIN "gfx/pokemon/aggron/back.2bpp.lz"
NumelFrontpic:              INCBIN "gfx/pokemon/numel/front.animated.2bpp.lz"
NumelBackpic:               INCBIN "gfx/pokemon/numel/back.2bpp.lz"


SECTION "Pics 12", ROMX
;180

CameruptFrontpic:           INCBIN "gfx/pokemon/camerupt/front.animated.2bpp.lz"
CameruptBackpic:            INCBIN "gfx/pokemon/camerupt/back.2bpp.lz"
RoseliaFrontpic:            INCBIN "gfx/pokemon/roselia/front.animated.2bpp.lz"
RoseliaBackpic:             INCBIN "gfx/pokemon/roselia/back.2bpp.lz"
RoseradeFrontpic:           INCBIN "gfx/pokemon/roserade/front.animated.2bpp.lz"
RoseradeBackpic:            INCBIN "gfx/pokemon/roserade/back.2bpp.lz"
CarvanhaFrontpic:           INCBIN "gfx/pokemon/carvanha/front.animated.2bpp.lz"
CarvanhaBackpic:            INCBIN "gfx/pokemon/carvanha/back.2bpp.lz"
SharpedoFrontpic:           INCBIN "gfx/pokemon/sharpedo/front.animated.2bpp.lz"
SharpedoBackpic:            INCBIN "gfx/pokemon/sharpedo/back.2bpp.lz"
SwabluFrontpic:             INCBIN "gfx/pokemon/swablu/front.animated.2bpp.lz"
SwabluBackpic:              INCBIN "gfx/pokemon/swablu/back.2bpp.lz"
AltariaFrontpic:            INCBIN "gfx/pokemon/altaria/front.animated.2bpp.lz"
AltariaBackpic:             INCBIN "gfx/pokemon/altaria/back.2bpp.lz"
ShuppetFrontpic:            INCBIN "gfx/pokemon/shuppet/front.animated.2bpp.lz"
ShuppetBackpic:             INCBIN "gfx/pokemon/shuppet/back.2bpp.lz"
BanetteFrontpic:            INCBIN "gfx/pokemon/banette/front.animated.2bpp.lz"
BanetteBackpic:             INCBIN "gfx/pokemon/banette/back.2bpp.lz"
CuboneFrontpic:             INCBIN "gfx/pokemon/cubone/front.animated.2bpp.lz"
CuboneBackpic:              INCBIN "gfx/pokemon/cubone/back.2bpp.lz"
KangaskhanFrontpic:         INCBIN "gfx/pokemon/kangaskhan/front.animated.2bpp.lz"
KangaskhanBackpic:          INCBIN "gfx/pokemon/kangaskhan/back.2bpp.lz"
MarowakFrontpic:            INCBIN "gfx/pokemon/marowak/front.animated.2bpp.lz"
MarowakBackpic:             INCBIN "gfx/pokemon/marowak/back.2bpp.lz"
GlameowFrontpic:            INCBIN "gfx/pokemon/glameow/front.animated.2bpp.lz"
GlameowBackpic:             INCBIN "gfx/pokemon/glameow/back.2bpp.lz"
PuruglyFrontpic:            INCBIN "gfx/pokemon/purugly/front.animated.2bpp.lz"
PuruglyBackpic:             INCBIN "gfx/pokemon/purugly/back.2bpp.lz"
TropiusFrontpic:            INCBIN "gfx/pokemon/tropius/front.animated.2bpp.lz"
TropiusBackpic:             INCBIN "gfx/pokemon/tropius/back.2bpp.lz"

SECTION "Pics 13", ROMX
;195

TorkoalFrontpic:            INCBIN "gfx/pokemon/torkoal/front.animated.2bpp.lz"
TorkoalBackpic:             INCBIN "gfx/pokemon/torkoal/back.2bpp.lz"
LaprasFrontpic:             INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
LaprasBackpic:              INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
RhyhornFrontpic:            INCBIN "gfx/pokemon/rhyhorn/front.animated.2bpp.lz"
RhyhornBackpic:             INCBIN "gfx/pokemon/rhyhorn/back.2bpp.lz"
RhydonFrontpic:             INCBIN "gfx/pokemon/rhydon/front.animated.2bpp.lz"
RhydonBackpic:              INCBIN "gfx/pokemon/rhydon/back.2bpp.lz"
ShellderFrontpic:           INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
ShellderBackpic:            INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
CloysterFrontpic:           INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
CloysterBackpic:            INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
SnoruntFrontpic:            INCBIN "gfx/pokemon/snorunt/front.animated.2bpp.lz"
SnoruntBackpic:             INCBIN "gfx/pokemon/snorunt/back.2bpp.lz"
GlalieFrontpic:             INCBIN "gfx/pokemon/glalie/front.animated.2bpp.lz"
GlalieBackpic:              INCBIN "gfx/pokemon/glalie/back.2bpp.lz"
FroslassFrontpic:           INCBIN "gfx/pokemon/froslass/front.animated.2bpp.lz"
FroslassBackpic:            INCBIN "gfx/pokemon/froslass/back.2bpp.lz"
PonytaFrontpic:             INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
PonytaBackpic:              INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
RapidashFrontpic:           INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
RapidashBackpic:            INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
StantlerFrontpic:           INCBIN "gfx/pokemon/stantler/front.animated.2bpp.lz"
StantlerBackpic:            INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
TaurosFrontpic:             INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
TaurosBackpic:              INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
MiltankFrontpic:            INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
MiltankBackpic:             INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
SnorlaxFrontpic:            INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
SnorlaxBackpic:             INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"





SECTION "Pics 14", ROMX
;210

ChanseyFrontpic:            INCBIN "gfx/pokemon/chansey/front.animated.2bpp.lz"
ChanseyBackpic:             INCBIN "gfx/pokemon/chansey/back.2bpp.lz"
BlisseyFrontpic:            INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
BlisseyBackpic:             INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
RioluFrontpic:              INCBIN "gfx/pokemon/riolu/front.animated.2bpp.lz"
RioluBackpic:               INCBIN "gfx/pokemon/riolu/back.2bpp.lz"
LucarioFrontpic:            INCBIN "gfx/pokemon/lucario/front.animated.2bpp.lz"
LucarioBackpic:             INCBIN "gfx/pokemon/lucario/back.2bpp.lz"
SurskitFrontpic:            INCBIN "gfx/pokemon/surskit/front.animated.2bpp.lz"
SurskitBackpic:             INCBIN "gfx/pokemon/surskit/back.2bpp.lz"
MasquerainFrontpic:         INCBIN "gfx/pokemon/masquerain/front.animated.2bpp.lz"
MasquerainBackpic:          INCBIN "gfx/pokemon/masquerain/back.2bpp.lz"
BaltoyFrontpic:             INCBIN "gfx/pokemon/baltoy/front.animated.2bpp.lz"
BaltoyBackpic:              INCBIN "gfx/pokemon/baltoy/back.2bpp.lz"
ClaydolFrontpic:            INCBIN "gfx/pokemon/claydol/front.animated.2bpp.lz"
ClaydolBackpic:             INCBIN "gfx/pokemon/claydol/back.2bpp.lz"
ScytherFrontpic:            INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
ScytherBackpic:             INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
ScizorFrontpic:             INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
ScizorBackpic:              INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
SlowpokeFrontpic:           INCBIN "gfx/pokemon/slowpoke/front.animated.2bpp.lz"
SlowpokeBackpic:            INCBIN "gfx/pokemon/slowpoke/back.2bpp.lz"
SlowbroFrontpic:            INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
SlowbroBackpic:             INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
SlowkingFrontpic:           INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
SlowkingBackpic:            INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
JynxFrontpic:               INCBIN "gfx/pokemon/jynx/front.animated.2bpp.lz"
JynxBackpic:                INCBIN "gfx/pokemon/jynx/back.2bpp.lz"
AbsolFrontpic:              INCBIN "gfx/pokemon/absol/front.animated.2bpp.lz"
AbsolBackpic:               INCBIN "gfx/pokemon/absol/back.2bpp.lz"

SECTION "Pics 15", ROMX
;225

HoothootFrontpic:           INCBIN "gfx/pokemon/hoothoot/front.animated.2bpp.lz"
HoothootBackpic:            INCBIN "gfx/pokemon/hoothoot/back.2bpp.lz"
NoctowlFrontpic:            INCBIN "gfx/pokemon/noctowl/front.animated.2bpp.lz"
NoctowlBackpic:             INCBIN "gfx/pokemon/noctowl/back.2bpp.lz"
SableyeFrontpic:            INCBIN "gfx/pokemon/sableye/front.animated.2bpp.lz"
SableyeBackpic:             INCBIN "gfx/pokemon/sableye/back.2bpp.lz"
EeveeFrontpic:              INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
EeveeBackpic:               INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
VaporeonFrontpic:           INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
VaporeonBackpic:            INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
JolteonFrontpic:            INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
JolteonBackpic:             INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
FlareonFrontpic:            INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FlareonBackpic:             INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
EspeonFrontpic:             INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
EspeonBackpic:              INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
UmbreonFrontpic:            INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
UmbreonBackpic:             INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
ShellosFrontpic:            INCBIN "gfx/pokemon/shellos/front.animated.2bpp.lz"
ShellosBackpic:             INCBIN "gfx/pokemon/shellos/back.2bpp.lz"
GastrodonFrontpic:          INCBIN "gfx/pokemon/gastrodon/front.animated.2bpp.lz"
GastrodonBackpic:           INCBIN "gfx/pokemon/gastrodon/back.2bpp.lz"
PorygonFrontpic:            INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
PorygonBackpic:             INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
Porygon2Frontpic:           INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
Porygon2Backpic:            INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
AerodactylFrontpic:         INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
AerodactylBackpic:          INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
KabutoFrontpic:             INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
KabutoBackpic:              INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"


SECTION "Pics 16", ROMX
;240

KabutopsFrontpic:           INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
KabutopsBackpic:            INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
LileepFrontpic:             INCBIN "gfx/pokemon/lileep/front.animated.2bpp.lz"
LileepBackpic:              INCBIN "gfx/pokemon/lileep/back.2bpp.lz"
CradilyFrontpic:            INCBIN "gfx/pokemon/cradily/front.animated.2bpp.lz"
CradilyBackpic:             INCBIN "gfx/pokemon/cradily/back.2bpp.lz"
DratiniFrontpic:            INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
DratiniBackpic:             INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
DragonairFrontpic:          INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
DragonairBackpic:           INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
DragoniteFrontpic:          INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
DragoniteBackpic:           INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
LarvitarFrontpic:           INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
LarvitarBackpic:            INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
PupitarFrontpic:            INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
PupitarBackpic:             INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
TyranitarFrontpic:          INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
TyranitarBackpic:           INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
BeldumFrontpic:             INCBIN "gfx/pokemon/beldum/front.animated.2bpp.lz"
BeldumBackpic:              INCBIN "gfx/pokemon/beldum/back.2bpp.lz"
MetangFrontpic:             INCBIN "gfx/pokemon/metang/front.animated.2bpp.lz"
MetangBackpic:              INCBIN "gfx/pokemon/metang/back.2bpp.lz"
MetagrossFrontpic:          INCBIN "gfx/pokemon/metagross/front.animated.2bpp.lz"
MetagrossBackpic:           INCBIN "gfx/pokemon/metagross/back.2bpp.lz"
GibleFrontpic:              INCBIN "gfx/pokemon/gible/front.animated.2bpp.lz"
GibleBackpic:               INCBIN "gfx/pokemon/gible/back.2bpp.lz"
GabiteFrontpic:             INCBIN "gfx/pokemon/gabite/front.animated.2bpp.lz"
GabiteBackpic:              INCBIN "gfx/pokemon/gabite/back.2bpp.lz"
GarchompFrontpic:           INCBIN "gfx/pokemon/garchomp/front.animated.2bpp.lz"
GarchompBackpic:            INCBIN "gfx/pokemon/garchomp/back.2bpp.lz"



SECTION "Pics 17", ROMX
;253

ArticunoFrontpic:           INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
ArticunoBackpic:            INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
ZapdosFrontpic:             INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
ZapdosBackpic:              INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
MoltresFrontpic:            INCBIN "gfx/pokemon/moltres/front.animated.2bpp.lz"
MoltresBackpic:             INCBIN "gfx/pokemon/moltres/back.2bpp.lz"
RaikouFrontpic:             INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
RaikouBackpic:              INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
SuicuneFrontpic:            INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
SuicuneBackpic:             INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
EnteiFrontpic:              INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
EnteiBackpic:               INCBIN "gfx/pokemon/entei/back.2bpp.lz"
MewtwoFrontpic:             INCBIN "gfx/pokemon/mewtwo/front.animated.2bpp.lz"
MewtwoBackpic:              INCBIN "gfx/pokemon/mewtwo/back.2bpp.lz"
LatiasFrontpic:             INCBIN "gfx/pokemon/latias/front.animated.2bpp.lz"
LatiasBackpic:              INCBIN "gfx/pokemon/latias/back.2bpp.lz"
LatiosFrontpic:             INCBIN "gfx/pokemon/latios/front.animated.2bpp.lz"
LatiosBackpic:              INCBIN "gfx/pokemon/latios/back.2bpp.lz"
HeatranFrontpic:            INCBIN "gfx/pokemon/heatran/front.animated.2bpp.lz"
HeatranBackpic:             INCBIN "gfx/pokemon/heatran/back.2bpp.lz"
CresseliaFrontpic:          INCBIN "gfx/pokemon/cresselia/front.animated.2bpp.lz"
CresseliaBackpic:           INCBIN "gfx/pokemon/cresselia/back.2bpp.lz"
GiratinaFrontpic:           INCBIN "gfx/pokemon/giratina/front.animated.2bpp.lz"
GiratinaBackpic:            INCBIN "gfx/pokemon/giratina/back.2bpp.lz"
TreyPic:                    INCBIN "gfx/trainers/trey.2bpp.lz"
DariaPic:                   INCBIN "gfx/trainers/daria.2bpp.lz"
AnnabellePic:               INCBIN "gfx/trainers/annabelle.2bpp.lz"
Eri1Pic:                    INCBIN "gfx/trainers/eri.2bpp.lz"
Tsubaki1Pic:                INCBIN "gfx/trainers/tsubaki.2bpp.lz"
BeppiPic:                   INCBIN "gfx/trainers/beppi.2bpp.lz"



SECTION "Pics 18", ROMX

Indigo1Pic:                  INCBIN "gfx/trainers/indigo.2bpp.lz"
Indigo2Pic:                 INCBIN "gfx/trainers/indigo2.2bpp.lz"
Eri2Pic:                    INCBIN "gfx/trainers/eri2.2bpp.lz"
Tsubaki2Pic:                INCBIN "gfx/trainers/tsubaki2.2bpp.lz"
Lorelei2Pic:                INCBIN "gfx/trainers/lorelei2.2bpp.lz"
BrunoPic:                   INCBIN "gfx/trainers/bruno.2bpp.lz"
MistyPic:                   INCBIN "gfx/trainers/misty.2bpp.lz"
BrockPic:                   INCBIN "gfx/trainers/brock.2bpp.lz"
AgathaPic:                  INCBIN "gfx/trainers/agatha.2bpp.lz"
WhitneyPic:                 INCBIN "gfx/trainers/whitney.2bpp.lz"
MysticalmanPic:             INCBIN "gfx/trainers/mysticalman.2bpp.lz"
SilverPic:                  INCBIN "gfx/trainers/silver.2bpp.lz"
ChampionPic:                INCBIN "gfx/trainers/champion.2bpp.lz"
MortyPic:                   INCBIN "gfx/trainers/morty.2bpp.lz"
SabrinaPic:                 INCBIN "gfx/trainers/sabrina.2bpp.lz"
GiovanniPic:                INCBIN "gfx/trainers/giovanni.2bpp.lz"
ClairPic:                   INCBIN "gfx/trainers/clair.2bpp.lz"
KarenPic:                   INCBIN "gfx/trainers/karen.2bpp.lz"
RedPic:                     INCBIN "gfx/trainers/red.2bpp.lz"
BluePic:                    INCBIN "gfx/trainers/blue.2bpp.lz"
GreenPic:                   INCBIN "gfx/trainers/green.2bpp.lz"
MorganPic:                  INCBIN "gfx/trainers/morgan.2bpp.lz"
ViolaPic:                   INCBIN "gfx/trainers/viola.2bpp.lz"
Viola2Pic:                  INCBIN "gfx/trainers/viola2.2bpp.lz"
JamzMPic:                   INCBIN "gfx/trainers/jamzm.2bpp.lz"
JamzFPic:                   INCBIN "gfx/trainers/jamzf.2bpp.lz"
GruntmPic:                  INCBIN "gfx/trainers/grunt_m.2bpp.lz"
GruntfPic:                  INCBIN "gfx/trainers/grunt_f.2bpp.lz"
ExecutivemPic:              INCBIN "gfx/trainers/executive_m.2bpp.lz"
ExecutivefPic:              INCBIN "gfx/trainers/executive_f.2bpp.lz"


SECTION "Pics 19", ROMX

JessiePic:                  INCBIN "gfx/trainers/jessie.2bpp.lz"
JamesPic:                   INCBIN "gfx/trainers/james.2bpp.lz"
BurglarPic:                 INCBIN "gfx/trainers/burglar.2bpp.lz"
FirebreatherPic:            INCBIN "gfx/trainers/firebreather.2bpp.lz"
JugglerPic:                 INCBIN "gfx/trainers/juggler.2bpp.lz"
BlackbeltTPic:              INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
PsychicTPic:                INCBIN "gfx/trainers/psychic_t.2bpp.lz"
PicnickerPic:               INCBIN "gfx/trainers/picnicker.2bpp.lz"
CamperPic:                  INCBIN "gfx/trainers/camper.2bpp.lz"
SagePic:                    INCBIN "gfx/trainers/sage.2bpp.lz"
MediumPic:                  INCBIN "gfx/trainers/medium.2bpp.lz"
BoarderPic:                 INCBIN "gfx/trainers/boarder.2bpp.lz"
PokefanmPic:                INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
KimonoGirlPic:              INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
PokefanfPic:                INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
OfficerPic:                 INCBIN "gfx/trainers/officer.2bpp.lz"
OfficerFPic:                INCBIN "gfx/trainers/officerf.2bpp.lz"
NursePic:                   INCBIN "gfx/trainers/nurse.2bpp.lz"
GuitaristPic:               INCBIN "gfx/trainers/guitarist.2bpp.lz"
HikerPic:                   INCBIN "gfx/trainers/hiker.2bpp.lz"
BikerPic:                   INCBIN "gfx/trainers/biker.2bpp.lz"
CueBallPic:                 INCBIN "gfx/trainers/cueball.2bpp.lz"
ScientistPic:               INCBIN "gfx/trainers/scientist.2bpp.lz"
YoungsterPic:               INCBIN "gfx/trainers/youngster.2bpp.lz"
LassPic:                    INCBIN "gfx/trainers/lass.2bpp.lz"
CooltrainermPic:            INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
CooltrainerfPic:            INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
BeautyPic:                  INCBIN "gfx/trainers/beauty.2bpp.lz"
GamblerPic:                 INCBIN "gfx/trainers/gambler.2bpp.lz"
PokemaniacPic:              INCBIN "gfx/trainers/pokemaniac.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX
GentlemanPic:               INCBIN "gfx/trainers/gentleman.2bpp.lz"
SkierPic:                   INCBIN "gfx/trainers/skier.2bpp.lz"
BugCatcherPic:              INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
FisherPic:                  INCBIN "gfx/trainers/fisher.2bpp.lz"
SwimmermPic:                INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SwimmerfPic:                INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
SailorPic:                  INCBIN "gfx/trainers/sailor.2bpp.lz"
SuperNerdPic:               INCBIN "gfx/trainers/super_nerd.2bpp.lz"
CoolTrainerGreenPic:        INCBIN "gfx/trainers/cooltrainer_g.2bpp.lz"
CoolTrainerAquaPic:         INCBIN "gfx/trainers/cooltrainer_a.2bpp.lz"
ChuckPic:                   INCBIN "gfx/trainers/chuck.2bpp.lz"
PokemonProfPic:             INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:                     INCBIN "gfx/trainers/cal.2bpp.lz"
WillPic:                    INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:               INCBIN "gfx/trainers/schoolboy.2bpp.lz"
ErikaPic:                   INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:                  INCBIN "gfx/trainers/janine.2bpp.lz"
HagaPic:                    INCBIN "gfx/trainers/haga.2bpp.lz"
Rival1Pic:                  INCBIN "gfx/trainers/rival1.2bpp.lz"
BlainePic:                  INCBIN "gfx/trainers/blaine.2bpp.lz"
JasminePic:                 INCBIN "gfx/trainers/jasmine.2bpp.lz"
Rival2Pic:                  INCBIN "gfx/trainers/rival2.2bpp.lz"
LtSurgePic:                 INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:                 INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:                     INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
BirdKeeperPic:              INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:                 INCBIN "gfx/trainers/falkner.2bpp.lz"
KogaPic:                    INCBIN "gfx/trainers/koga.2bpp.lz"
TwinsPic:                   INCBIN "gfx/trainers/twins.2bpp.lz"
PrycePic:                   INCBIN "gfx/trainers/pryce.2bpp.lz"

SECTION "Pics 21", ROMX
UnownEFrontpic:             INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"
UnownFBackpic:              INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"
UnownDFrontpic:             INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
UnownWFrontpic:             INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
UnownCFrontpic:             INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
UnownZFrontpic:             INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
UnownHBackpic:              INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"
UnownGFrontpic:             INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
UnownVFrontpic:             INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
UnownSFrontpic:             INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
UnownOFrontpic:             INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:             INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
UnownHFrontpic:             INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
UnownDBackpic:              INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"

SECTION "Pics 22", ROMX
UnownKFrontpic:             INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
UnownBFrontpic:             INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
UnownXFrontpic:             INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:             INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
UnownJFrontpic:             INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
UnownLFrontpic:             INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
UnownMFrontpic:             INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:             INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
UnownAFrontpic:             INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
UnownUFrontpic:             INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
UnownQFrontpic:             INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:             INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:              INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
UnownYFrontpic:             INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:              INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:             INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:              INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
UnownSBackpic:              INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"

SECTION "Pics 23", ROMX
UnownRFrontpic:             INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:              INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:              INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:              INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:              INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:              INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:              INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:              INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:              INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:              INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:              INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:              INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"

SECTION "Pics 24", ROMX

BattleGirlPic:              INCBIN "gfx/trainers/battlegirl.2bpp.lz"
KenjiPic:                   INCBIN "gfx/trainers/kenji.2bpp.lz"

UnownXBackpic:              INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:              INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:              INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:              INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:              INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:              INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:              INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:              INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"