SECTION "Sprites 1", ROMX

ChrisSpriteGFX::               INCBIN "gfx/sprites/chris.2bpp"
ChrisBikeSpriteGFX::           INCBIN "gfx/sprites/chris_bike.2bpp"
KrisSpriteGFX::                INCBIN "gfx/sprites/kris.2bpp"
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/kris_bike.2bpp"
SurfSpriteGFX::                INCBIN "gfx/sprites/surf.2bpp"
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surfing_pikachu.2bpp"
TreySpriteGFX::                INCBIN "gfx/sprites/01/trey.2bpp"
DariaSpriteGFX::               INCBIN "gfx/sprites/01/trey.2bpp"
AnnabelleSpriteGFX::           INCBIN "gfx/sprites/01/annabelle.2bpp"
EriSpriteGFX::                 INCBIN "gfx/sprites/01/eri.2bpp"
TsubakiSpriteGFX::             INCBIN "gfx/sprites/01/tsubaki.2bpp"
BeppiSpriteGFX::               INCBIN "gfx/sprites/01/beppi.2bpp"
NeroSpriteGFX::                INCBIN "gfx/sprites/01/nero.2bpp"
LoreleiSpriteGFX::             INCBIN "gfx/sprites/01/lorelei.2bpp"
BrunoSpriteGFX::               INCBIN "gfx/sprites/01/bruno.2bpp"
MistySpriteGFX::               INCBIN "gfx/sprites/01/misty.2bpp"
BrockSpriteGFX::               INCBIN "gfx/sprites/01/brock.2bpp"
AgithaSpriteGFX::              INCBIN "gfx/sprites/01/agitha.2bpp"
WhitneySpriteGFX::             INCBIN "gfx/sprites/01/whitney.2bpp"
EusineSpriteGFX::              INCBIN "gfx/sprites/01/eusine.2bpp"
SilverSpriteGFX::              INCBIN "gfx/sprites/01/silver.2bpp"
LanceSpriteGFX::               INCBIN "gfx/sprites/01/lance.2bpp"
MortySpriteGFX::               INCBIN "gfx/sprites/01/morty.2bpp"
SabrinaSpriteGFX::             INCBIN "gfx/sprites/01/sabrina.2bpp"
GiovanniSpriteGFX::            INCBIN "gfx/sprites/01/giovanni.2bpp"
KarenSpriteGFX::               INCBIN "gfx/sprites/01/karen.2bpp"
ClairSpriteGFX::               INCBIN "gfx/sprites/01/clair.2bpp"
RedSpriteGFX::                 INCBIN "gfx/sprites/01/red.2bpp"
BlueSpriteGFX::                INCBIN "gfx/sprites/01/blue.2bpp"
GreenSpriteGFX::               INCBIN "gfx/sprites/01/green.2bpp"
IndigoSpriteGFX::              INCBIN "gfx/sprites/01/indigo.2bpp"
ViolaSpriteGFX::               INCBIN "gfx/sprites/01/viola.2bpp"
IvySpriteGFX::                 INCBIN "gfx/sprites/01/ivy.2bpp"
OakSpriteGFX::                 INCBIN "gfx/sprites/01/oak.2bpp"
YoungsterSpriteGFX::           INCBIN "gfx/sprites/01/youngster.2bpp"
LassSpriteGFX::                INCBIN "gfx/sprites/01/lass.2bpp"
HikerSpriteGFX::               INCBIN "gfx/sprites/01/hiker.2bpp"
PicnickerSpriteGFX::           INCBIN "gfx/sprites/01/picnicker.2bpp"
CamperSpriteGFX::              INCBIN "gfx/sprites/01/camper.2bpp"
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/01/bugcatcher.2bpp"
CooltrainermSpriteGFX::        INCBIN "gfx/sprites/01/cooltrainerm.2bpp"
CooltrainerfSpriteGFX::        INCBIN "gfx/sprites/01/cooltrainerf.2bpp"


SECTION "Sprites 2", ROMX

SageSpriteGFX::                INCBIN "gfx/sprites/01/sage.2bpp"
MediumSpriteGFX::              INCBIN "gfx/sprites/01/medium.2bpp"
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/01/kimonogirl.2bpp"
PsychicSpriteGFX::             INCBIN "gfx/sprites/01/psychic.2bpp"
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/01/supernerd.2bpp"
PokemaniacSpriteGFX::          INCBIN "gfx/sprites/01/pokemaniac.2bpp"
GentlemanSpriteGFX::           INCBIN "gfx/sprites/01/gentleman.2bpp"
BeautySpriteGFX::              INCBIN "gfx/sprites/01/beauty.2bpp"
TamerSpriteGFX::               INCBIN "gfx/sprites/01/tamer.2bpp"
FirebreatherSpriteGFX::        INCBIN "gfx/sprites/01/firebreather.2bpp"
JugglerSpriteGFX::             INCBIN "gfx/sprites/01/juggler.2bpp"
ScientistSpriteGFX::           INCBIN "gfx/sprites/01/scientist.2bpp"
GamblerSpriteGFX::             INCBIN "gfx/sprites/01/gambler.2bpp"
CueballSpriteGFX::             INCBIN "gfx/sprites/01/cueball.2bpp"
BikerSpriteGFX::               INCBIN "gfx/sprites/01/biker.2bpp"
BlackbeltSpriteGFX::           INCBIN "gfx/sprites/01/blackbelt.2bpp"
FisherSpriteGFX::              INCBIN "gfx/sprites/01/fisher.2bpp"
SailorSpriteGFX::              INCBIN "gfx/sprites/01/sailor.2bpp"
PokefanmSpriteGFX::            INCBIN "gfx/sprites/01/pokefanm.2bpp"
PokefanfSpriteGFX::            INCBIN "gfx/sprites/01/pokefanf.2bpp"
BoarderSpriteGFX::             INCBIN "gfx/sprites/01/boarder.2bpp"
OfficerSpriteGFX::             INCBIN "gfx/sprites/01/officer.2bpp"
OfficerfSpriteGFX::            INCBIN "gfx/sprites/01/officerf.2bpp"
Nurse2SpriteGFX::              INCBIN "gfx/sprites/01/nurse2.2bpp"
RocketSpriteGFX::              INCBIN "gfx/sprites/01/rocket.2bpp"
RocketfSpriteGFX::             INCBIN "gfx/sprites/01/rocketf.2bpp"
ArcherSpriteGFX::              INCBIN "gfx/sprites/01/archer.2bpp"
AriannaSpriteGFX::             INCBIN "gfx/sprites/01/arianna.2bpp"
JessieSpriteGFX::              INCBIN "gfx/sprites/01/jessie.2bpp"
JamesSpriteGFX::               INCBIN "gfx/sprites/01/james.2bpp"
JamzmSpriteGFX::               INCBIN "gfx/sprites/01/jamzm.2bpp"
JamzfSpriteGFX::               INCBIN "gfx/sprites/01/jamzf.2bpp"
GymGuideSpriteGFX::            INCBIN "gfx/sprites/01/gymguide.2bpp"
GuardSpriteGFX::               INCBIN "gfx/sprites/01/guard.2bpp"



SECTION "Sprites 3", ROMX

GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp"
BillSpriteGFX::                INCBIN "gfx/sprites/bill.2bpp"
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp"
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp"
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp"
DaisySpriteGFX::               INCBIN "gfx/sprites/daisy.2bpp"
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp"
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp"
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp"
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_guy.2bpp"
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_girl.2bpp"
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp"
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp"
UnusedGuySpriteGFX::           INCBIN "gfx/sprites/unused_guy.2bpp"
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp"
CaptainSpriteGFX::             INCBIN "gfx/sprites/captain.2bpp"
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp"
OldLinkReceptionistSpriteGFX:: INCBIN "gfx/sprites/old_link_receptionist.2bpp"
JanineSpriteGFX::              INCBIN "gfx/sprites/janine.2bpp"
RockSpriteGFX::                INCBIN "gfx/sprites/rock.2bpp"
BoulderSpriteGFX::             INCBIN "gfx/sprites/boulder.2bpp"
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp"
FamicomSpriteGFX::             INCBIN "gfx/sprites/famicom.2bpp"
FruitTreeSpriteGFX::           INCBIN "gfx/sprites/fruit_tree.2bpp"
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp"
SilverTrophySpriteGFX::        INCBIN "gfx/sprites/silver_trophy.2bpp"
PokeBallSpriteGFX::            INCBIN "gfx/sprites/poke_ball.2bpp"
PokedexSpriteGFX::             INCBIN "gfx/sprites/pokedex.2bpp"
PaperSpriteGFX::               INCBIN "gfx/sprites/paper.2bpp"
VirtualBoySpriteGFX::          INCBIN "gfx/sprites/virtual_boy.2bpp"
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp"
MonsterSpriteGFX::             INCBIN "gfx/sprites/monster.2bpp"

